/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;
import jalan.jalan.*;

/**
 *
 * @author akhdan
 */
public class gui extends javax.swing.JFrame {

    String a1,b2,c3;
    String d4;
    public gui() {
        initComponents();
    }
    
    
    public String a1(){
        this.a1();
        return a1();
    }
    public String b2(){
        this.b2();
        return b2();
    }
    public String c3(){
        this.c3();
        return c3;
    }
    public String d4(){
        this.d4();
        return d4();
    }
    
    
    public String nama(String a){
        this.nama(a);
        return a+a1();
    }
    public String nama_panjang(String b){
        this.nama_panjang(b);
        return b+b2();
        
    }
    public String temap_tinggal(String c){
        this.temap_tinggal(c);
        return c+c3();
    }
    public String usia(int d){
        this.usia(d);
        return d+d4();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Nama = new javax.swing.JLabel();
        Nama_Panjang = new javax.swing.JLabel();
        Tempat_Tinggal = new javax.swing.JLabel();
        Usia = new javax.swing.JLabel();
        NAMA = new javax.swing.JTextField();
        NAMA_PANJANG = new javax.swing.JTextField();
        TEMPAT_TINGGAL = new javax.swing.JTextField();
        USIA = new javax.swing.JTextField();
        Tombol_4 = new javax.swing.JButton();
        TOMBOL_1 = new javax.swing.JButton();
        TOMBOL_2 = new javax.swing.JButton();
        TOMBOL3 = new javax.swing.JButton();
        Text = new javax.swing.JTextField();
        Text2 = new javax.swing.JTextField();
        Text3 = new javax.swing.JTextField();
        Text4 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Nama.setText("NAMA");

        Nama_Panjang.setText("NAMA PANJANG");

        Tempat_Tinggal.setText("TEMPAT TINGGAL");

        Usia.setText("USIA");
        Usia.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                UsiaAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        NAMA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NAMAActionPerformed(evt);
            }
        });

        NAMA_PANJANG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NAMA_PANJANGActionPerformed(evt);
            }
        });

        TEMPAT_TINGGAL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TEMPAT_TINGGALActionPerformed(evt);
            }
        });

        USIA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                USIAActionPerformed(evt);
            }
        });

        Tombol_4.setText("ENTER");
        Tombol_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Tombol_4ActionPerformed(evt);
            }
        });

        TOMBOL_1.setText("ENTER");
        TOMBOL_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TOMBOL_1ActionPerformed(evt);
            }
        });

        TOMBOL_2.setText("ENTER");
        TOMBOL_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TOMBOL_2ActionPerformed(evt);
            }
        });

        TOMBOL3.setText("ENTER");
        TOMBOL3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TOMBOL3ActionPerformed(evt);
            }
        });

        Text.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextActionPerformed(evt);
            }
        });

        Text2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Text2ActionPerformed(evt);
            }
        });

        Text3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Text3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Text4, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Tempat_Tinggal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Nama_Panjang)
                            .addComponent(Nama, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Usia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(NAMA_PANJANG)
                            .addComponent(TEMPAT_TINGGAL)
                            .addComponent(USIA)
                            .addComponent(NAMA))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Tombol_4)
                                    .addComponent(TOMBOL_1)
                                    .addComponent(TOMBOL_2))
                                .addGap(9, 9, 9))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(TOMBOL3)
                                .addContainerGap())))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Text2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Text)
                            .addComponent(Text3, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Nama)
                    .addComponent(NAMA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TOMBOL_1))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Nama_Panjang)
                    .addComponent(NAMA_PANJANG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TOMBOL_2))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Tempat_Tinggal)
                    .addComponent(TEMPAT_TINGGAL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TOMBOL3))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Usia)
                    .addComponent(USIA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Tombol_4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Text2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Text3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(Text4))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Tombol_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Tombol_4ActionPerformed
       String Usia=USIA.getText().toString().trim();
       if(Usia!=d4)
       {
          Text4.setText("Benar");
       } 
    }//GEN-LAST:event_Tombol_4ActionPerformed

    private void NAMA_PANJANGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NAMA_PANJANGActionPerformed
        
    }//GEN-LAST:event_NAMA_PANJANGActionPerformed

    private void TEMPAT_TINGGALActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TEMPAT_TINGGALActionPerformed
       
    }//GEN-LAST:event_TEMPAT_TINGGALActionPerformed

    private void USIAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_USIAActionPerformed
         
    }//GEN-LAST:event_USIAActionPerformed

    private void NAMAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NAMAActionPerformed
 
    }//GEN-LAST:event_NAMAActionPerformed

    private void UsiaAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_UsiaAncestorAdded
        
    }//GEN-LAST:event_UsiaAncestorAdded

    private void TOMBOL_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TOMBOL_1ActionPerformed
       String Nama=NAMA.getText().toString().trim();
       if(Nama!=a1)
       {
          Text.setText("Benar");
       } 
       
    }//GEN-LAST:event_TOMBOL_1ActionPerformed

    private void TOMBOL_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TOMBOL_2ActionPerformed
        String Nama_Panjang = NAMA_PANJANG.getText().toString().trim();
        if(Nama_Panjang!=b2)
       {
          Text2.setText("Benar");
       } 
    }//GEN-LAST:event_TOMBOL_2ActionPerformed

    private void TextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextActionPerformed
   
    }//GEN-LAST:event_TextActionPerformed

    private void TOMBOL3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TOMBOL3ActionPerformed
        String Tempat_Tinggal = TEMPAT_TINGGAL.getText().toString().trim();
        if(Tempat_Tinggal!=c3)
       {
          Text3.setText("Benar");
       } 
    }//GEN-LAST:event_TOMBOL3ActionPerformed

    private void Text2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Text2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Text2ActionPerformed

    private void Text3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Text3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Text3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new gui().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField NAMA;
    private javax.swing.JTextField NAMA_PANJANG;
    private javax.swing.JLabel Nama;
    private javax.swing.JLabel Nama_Panjang;
    private javax.swing.JTextField TEMPAT_TINGGAL;
    private javax.swing.JButton TOMBOL3;
    private javax.swing.JButton TOMBOL_1;
    private javax.swing.JButton TOMBOL_2;
    private javax.swing.JLabel Tempat_Tinggal;
    private javax.swing.JTextField Text;
    private javax.swing.JTextField Text2;
    private javax.swing.JTextField Text3;
    private javax.swing.JTextField Text4;
    private javax.swing.JButton Tombol_4;
    private javax.swing.JTextField USIA;
    private javax.swing.JLabel Usia;
    // End of variables declaration//GEN-END:variables
}
